//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monk15.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Monk15Entities : DbContext
    {
        public Monk15Entities()
            : base("name=Monk15Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<Community> Communities { get; set; }
        public virtual DbSet<CommunityLogo> CommunityLogos { get; set; }
        public virtual DbSet<CommunityMember> CommunityMembers { get; set; }
        public virtual DbSet<Influencer> Influencers { get; set; }
        public virtual DbSet<Invite> Invites { get; set; }
        public virtual DbSet<KarmaProperty> KarmaProperties { get; set; }
        public virtual DbSet<Karma> Karmas { get; set; }
        public virtual DbSet<NFTVerification> NFTVerifications { get; set; }
        public virtual DbSet<OAuth_Providers> OAuth_Providers { get; set; }
        public virtual DbSet<PollOption> PollOptions { get; set; }
        public virtual DbSet<Quest> Quests { get; set; }
        public virtual DbSet<QuizQuestion> QuizQuestions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<SocialAccount> SocialAccounts { get; set; }
        public virtual DbSet<SocialStat> SocialStats { get; set; }
        public virtual DbSet<Sprint> Sprints { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskType> TaskTypes { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserTask> UserTasks { get; set; }
        public virtual DbSet<UserXP> UserXPs { get; set; }
        public virtual DbSet<WalletAuth> WalletAuths { get; set; }
    }
}
