//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monk15.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollOption
    {
        public int id { get; set; }
        public Nullable<int> task_id { get; set; }
        public string option_text { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
