//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monk15.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialStat
    {
        public int id { get; set; }
        public Nullable<int> influencer_id { get; set; }
        public string platform { get; set; }
        public string followers_count { get; set; }
        public string engagement_rate { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Influencer Influencer { get; set; }
    }
}
