//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monk15.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialAccount
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> community_id { get; set; }
        public string provider { get; set; }
        public string provider_id { get; set; }
        public string account_name { get; set; }
        public string profile_url { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Community Community { get; set; }
        public virtual User User { get; set; }
    }
}
