//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monk15.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.PollOptions = new HashSet<PollOption>();
            this.QuizQuestions = new HashSet<QuizQuestion>();
            this.UserTasks = new HashSet<UserTask>();
        }
    
        public int id { get; set; }
        public Nullable<int> karma_id { get; set; }
        public Nullable<int> quest_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public string platform { get; set; }
        public string icon_url { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<int> reward { get; set; }
        public Nullable<int> cooldown_seconds { get; set; }
        public string recurrence { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Karma Karma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PollOption> PollOptions { get; set; }
        public virtual Quest Quest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizQuestion> QuizQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTask> UserTasks { get; set; }
    }
}
