//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monk15.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string full_name { get; set; }
        public string profile_picture { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
    
        public virtual User User { get; set; }
    }
}
