//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monk15.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTask
    {
        public int id { get; set; }
        public Nullable<int> task_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string submission_text { get; set; }
        public string file_url { get; set; }
        public Nullable<int> poll_option_selected { get; set; }
        public string quiz_answer { get; set; }
        public Nullable<System.DateTime> submitted_at { get; set; }
        public string status { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
